[tox]
envlist =
       {py310, py311, py312, py313}-django52
       {py312, py313, py314}-django60
       {py312, py313, py314}-django61
       {py310, py311, py312, py313}-django52-mssqlpython
       {py312, py313, py314}-django60-mssqlpython
       {py312, py313, py314}-django61-mssqlpython

[testenv]
allowlist_externals =
    bash
passenv =
    MSSQL_*

setenv =
    PYTHONUNBUFFERED=1
    !mssqlpython: MSSQL_PYTHON_DRIVER=pyodbc
    mssqlpython: MSSQL_PYTHON_DRIVER=mssql_python

commands =
    python -m testapp.check_driver
    coverage run --parallel-mode manage.py test --noinput
    bash test.sh

deps =
    coverage==7.16.0; python_version >= "3.10"
    unittest-xml-reporting

    mssqlpython: mssql-python==1.15.0

    django52: django>=5.2,<5.3
    django60: django>=6.0,<6.1
    django61: django>=6.1,<6.2
