[tox]
envlist =
       {py310, py311, py312, py313}-django52
       {py312, py313, py314}-django60
       {py312, py313, py314}-django61

[testenv]
allowlist_externals =
    bash
passenv =
    MSSQL_*

commands =
    coverage run --parallel-mode manage.py test --noinput --parallel 1
    bash test.sh

deps =
    coverage==5.5
    unittest-xml-reporting

    django52: django>=5.2,<5.3
    django60: django>=6.0,<6.1
    django61: django>=6.1,<6.2
