DATA_TYPES = {
    'AutoField':         'int IDENTITY (1, 1)',
    'BooleanField':      'bit',
    'BooleanField':      'smallint',
    'CharField':         'nvarchar(%(max_length)s)',
    'CommaSeparatedIntegerField': 'nvarchar(%(max_length)s)',
    'DateField':         'datetime',
    'DateTimeField':     'datetime',
    'DecimalField':      'numeric(%(max_digits)s, %(decimal_places)s)',
    'FileField':         'nvarchar(254) ',
    'FilePathField':     'nvarchar(254) ',
    'FloatField':        'double precision',
    'ImageField':        'nvarchar(254)',
    'IntegerField':      'int',
    'IPAddressField':    'nvarchar(15)',
    'ManyToManyField':   None,
    'NullBooleanField':  'bit',
    'OneToOneField':     'int',
    'PhoneNumberField':  'nvarchar(20) ',
    #The check must be unique in for the database. Put random so the regresion test not complain about duplicate names
    'PositiveIntegerField': 'int CONSTRAINT [CK_int_pos_%(creation_counter)s_%(column)s] CHECK ([%(column)s] > 0)',    
    'PositiveSmallIntegerField': 'smallint CONSTRAINT [CK_smallint_pos_%(creation_counter)s_%(column)s] CHECK ([%(column)s] > 0)',
    'SlugField':         'nvarchar(%(max_length)s)',
    'SmallIntegerField': 'smallint',
    'TextField':         'ntext',
    'TimeField':         'datetime',
    'USStateField':      'nchar(2)',
}

