# Generated by Django 4.0.4 on 2022-06-07 15:37

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_multiple_autofield_to_bigauto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
