# Generated by Django 5.2.1 on 2025-05-27 12:44

from django.db import migrations, models
from django import VERSION as DJANGO_VERSION

class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_modelwithnullablefieldsofdifferenttypes'),
    ]

    operations = []
    
    if DJANGO_VERSION >= (5, 2):
        operations = [
            migrations.CreateModel(
                name='Release',
                fields=[
                    ('pk', models.CompositePrimaryKey('version', 'name', blank=True, editable=False, primary_key=True, serialize=False)),
                    ('version', models.IntegerField()),
                    ('name', models.CharField(max_length=20)),
                ],
            ),
        ]
 