# Generated by Django 5.2.11 on 2026-02-09 12:32

import django.db.models.deletion
from django.db import migrations, models


def create_schema(apps, schema_editor): 
    """
    This creates the schema in order to make the tests work!
    """
    connection = schema_editor.connection

    if connection.vendor == 'microsoft':
        sql = "IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'events') BEGIN EXEC('CREATE SCHEMA [events]') END"
        cursor = connection.cursor()
        cursor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_modelwithnullablefieldsofdifferenttypes'),
    ]

    operations = [
        migrations.RunPython(create_schema),
        migrations.CreateModel(
            name='ParentSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '[events].[ParentSchema]',
            },
        ),
        migrations.CreateModel(
            name='ChildSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.parentschema')),
            ],
            options={
                'db_table': '[events].[ChildSchema]',
            },
        ),
    ]
