# Generated by Django 5.2.12 on 2026-03-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_parentschema_childschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='DboSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '[dbo].[DefaultNameTable]',
            },
        ),
        migrations.CreateModel(
            name='UnusualSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '[unusual]]schema].[Unusual]]Table]',
            },
        ),
    ]
