# Generated by Django 6.0.5 on 2026-06-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_create_dboschema'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnusualSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': '[unusual]]schema].[Unusual]]Table]',
            },
        ),
        migrations.CreateModel(
            name='UnusualSchema2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'unusual]schema2.Unusual]Table2',
            },
        ),
        migrations.CreateModel(
            name='UnusualTable3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Unusual]Table3',
            },
        ),
    ]
